### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by vinibgoulart** [NandoGoulartt/cantinaIfsc#17]
### Produto
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [x] filter by string

### Cidade
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [x] filter by string

### Bairro
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [x] filter by string

### Carteirinha
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [x] filter by string

### Endereco
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [ ] filter by string

### Cliente
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [ ] filter by string

### Fornecedor
- [x] dao
- [x] service
- [x] service
- [x] create
- [x] read
- [x] update
- [ ] filter by string

### Funcionario
- [x] dao
- [x] service
- [x] create
- [x] read
- [x] update
- [ ] filter by string
